let seedData = [
  {
    name: "Cinnamon Roll Pancakes",
    ingredients: [
      "250 g Plain flour",
      "4 tsp Baking Powder",
      "1 tsp Sea salt",
      "480 ml milk",
      "4 tbsp Maple syrup",
      "6 tbsp margarine",
      "15 tbsp Brown sugar",
      "4 tbsp Cinnamon powder",
      "240 g Icing sugar",
      "50 ml water",
    ],
    instructions: [
      "In a bowl, whisk together flour, baking powder and salt. In a separate small bowl, whisk together milk and maple syrup.",
      "And the wet ingredients into the dry ingredients and whisk to combine.",
      "In a small bowl, combine together margarine, brown sugar and Cinnamon powder.",
      "Transfer the mixture to a pastry or zip-lock bag; snip-off one corner.",
      "Lightly grease a non-stick skillet. Pour a quarter cup of batter on to the skillet.",
      "Pipe a circular cinnamon swirl into the batter.",
      "When small bubbles appear on the center of the pancake- after about 4 minutes flip the pancake.",
      "Cook on the other side for about 1 minute. Repeat with the rest of the batter- adding oil to the skillet when needed.",
      "In a small bowl- combine confectioners sugar and water and whisk until smooth.",
      "Drizzle the glaze over the pancakes.",
    ],
    tags: [
      "snack",
      "dessert",
      "breakfast",
      "spices",
      "crowd pleaser",
      "american",
      "dairy",
      "frying",
      "sweet",
      "kid friendly",
    ],
    category: "breakfast",
    cuisine: "american",
    cook: "40 min.",
    servings: "8",
    image:
      "https://images.kitchenstories.io/communityImages/f3340059b06039432c0860160c0bfb9b_0d79bef2-6b2c-4280-ad30-fa56a60445b6.jpg",
  },
];
